made it easier to compile iFKO w/o ATLAS

diff --git a/iFKO/configure b/iFKO/configure
--- a/iFKO/configure
+++ b/iFKO/configure
@@ -1,12 +1,15 @@
 #!/bin/sh
-if [ $# -ne 4 ]
+fndex=0
+if [$# -eq 4]
+then
+   ext=$4
+   fndex=1
+elif [ $# -ne 3 ]
 then
    echo "Wrong number of parameters: $#"
-   echo "USAGE: extract gcc 'gccflags' 'defs' "
+   echo "USAGE: gcc 'gccflags' 'defs' [extract]"
    exit 1
 fi
-ext=$1
-shift
 gcc=$1
 shift
 flags=$1
@@ -37,6 +40,18 @@ then
    exit 1
 fi
 rm $blddir/TstBld974.txt
+
+if test $fndex -eq 0
+then
+   $gcc $flags -o extract $topdir/src/extract.c
+   ext=$blddir/extract
+   if [ ! -x $ext ]
+   then
+      echo "Unable to build extract with $gcc $flags!"
+      exit 2
+   fi
+fi
+
 #
 # Create the Make.inc needed to build
 #
@@ -55,8 +70,10 @@ echo "ARF=r" >> Make.inc
 echo "RANLIB=echo" >> Make.inc
 echo EXTRACT="$ext" >> Make.inc
 
-mkdir FKOsrc src bin include lib
+mkdir FKOsrc src include lib
 $ext -langM -b $topdir/base/hmake.base -o Makefile rout=Make.bin 
 $ext -langM -b $topdir/base/hmake.base -o src/Makefile rout=Make.isrc
 $ext -langM -b $topdir/base/hmake.base -o FKOsrc/Makefile rout=Make.fsrc
 $ext -langC -b $topdir/base/hmake.base -o include/fko_settings.h rout=fko_settings.h
+
+echo "\nConfigure done."
